### ISSUE TITLE
After adding task, app crashes 

### ISSUE THREAD

**Issue by Sppurswani** [cassandrale179/ci491_project#126]

**Comment by cassandrale179** [comment]
I cannot replicate this bug for some reason. Even when using the credentials provided by Pratik. If someone find the bug, can they quickly check the log to see what is the issue? Since my Add Task worked fine.

**Comment by juihanamshet** [comment]
I was able to replicate this bug. 
Caregiver account: juigiver@gmail.com
Caregivee account: juigivee@gmail.com

I added the first ever task for this caregivee. This is the log. 
![image](https://user-images.githubusercontent.com/32686593/109366276-02db0100-7861-11eb-87d5-d1c47d11e868.png)

**Comment by cassandrale179** [comment]
I try again with this account (juigiver) and (juigivee) and still can't find any error. However, I notice that the error seem to be point at line 81, which is where we initialize the color red and green. To be super safe, I remove those lines and put them in the displaySuccessMessage and displayErrorMessage instead to ensure the getApplication() is called after onCreate. I also make sure the view.getContext() is properly initialized before allow user to redirect. 

The changes are made in this PR here: https://github.com/cassandrale179/ci491_project/pull/142 
Can someone try to check out that branch and let me know if they still encounter the same error on their end?

**Comment by Sppurswani** [comment]
Yup that's what I found as well. I briefly looked up the error (since it was the same for another issue) and checking if the context exists seems the be the fix here
