### ISSUE TITLE
App crashed after caregiver sent a request to add caregivee

### ISSUE THREAD

**Issue by juihanamshet** [cassandrale179/ci491_project#132]
Caregiver account: juigiver@gmail.com
Caregivee account: juigivee@gmail.com 

Error 
![image](https://user-images.githubusercontent.com/32686593/109365112-69aaeb00-785e-11eb-95c9-41ff170e03b5.png)

The app crashed and reloaded the send requests page. When I login to the caregivee account, I see the request from caregiver.

**Comment by Sppurswani** [comment]
I believe my previous fix may have addressed this but I added some more checks just to be sure, will create a PR very soon!

**Comment by Sppurswani** [comment]
https://user-images.githubusercontent.com/30156526/109375271-8577b680-7889-11eb-8d69-3c3b74c099e4.mov
