### ISSUE TITLE
No hint setup for Caregivee's Profile

### ISSUE THREAD

**Issue by juihanamshet** [cassandrale179/ci491_project#135]
Caregiver account: juigiver@gmail.com
Caregivee account: juigivee@gmail.com 

When I clicked on View Profile for the Caregivee from the caregiver's account, it doesn't have a hint setup for the 3rd edittext. 
![image](https://user-images.githubusercontent.com/32686593/109365881-1e91d780-7860-11eb-802f-971e482ef77d.png)

**Comment by cassandrale179** [comment]
Fixed  in https://github.com/cassandrale179/ci491_project/pull/143 

<img width="400" alt="Screen Shot 2021-02-26 at 9 27 10 PM" src="https://user-images.githubusercontent.com/22923895/109372782-6a9d4600-7879-11eb-84c2-eac1a638c178.png">
