### ISSUE TITLE
List of rooms shows up in caregiver task page even though no rooms have been set up

### ISSUE THREAD

**Issue by juihanamshet** [cassandrale179/ci491_project#136]
Caregiver account - juigiver@gmail.com
Caregivee account - juigivee@gmail.com

The caregivee account doesn't have any rooms set up
![image](https://user-images.githubusercontent.com/32686593/109366082-85af8c00-7860-11eb-846a-a90fbb1d3a36.png)

From my caregiver account, I tried to set up tasks for the caregivee and I could see a list of rooms. These rooms should not be there right? 
![image](https://user-images.githubusercontent.com/32686593/109366129-99f38900-7860-11eb-9f66-b5a22a45f7e8.png)

**Comment by Sppurswani** [comment]
I believe this intentional - to test edit/add task functionality, since the rooms aren't setup for us. If I remember correctly, there is logic that says if there are no rooms yet, display this static list.

**Comment by juihanamshet** [comment]
Ah okay! I didn't know that, I'll close this bug.
