### ISSUE TITLE
App crashes when a task is deleted

### ISSUE THREAD

**Issue by juihanamshet** [cassandrale179/ci491_project#137]
Caregiver account - juigiver@gmail.com
Caregivee account - juigivee@gmail.com 

I added 3 tasks for the caregivee. I deleted the last one I created and the app threw an error and reloaded. The delete operation worked and it got removed from firebase too. 
![image](https://user-images.githubusercontent.com/32686593/109366396-564d4f00-7861-11eb-839f-32bb74437127.png)

**Comment by Sppurswani** [comment]
I believe this was also fixed on the push for issue #127. The fix is in line in TaskFragment.java

https://user-images.githubusercontent.com/30156526/109375508-46e2fb80-788b-11eb-8567-16a34c410e81.mov
