### ISSUE TITLE
App crashed when a task was assigned

### ISSUE THREAD

**Issue by juihanamshet** [cassandrale179/ci491_project#138]
Caregiver account - juigiver@gmail.com
Caregivee account - juigivee@gmail.com

The caregivee has 2 tasks - Walk the dog and brush your teeth. I assigned walk the dog and clicked on Assign Task button. The app crashed with the below error
![image](https://user-images.githubusercontent.com/32686593/109366619-decbef80-7861-11eb-9025-51ff997bef22.png)

**Comment by juihanamshet** [comment]
The tasks seem to have been assigned though even though the error occurred.

**Comment by cassandrale179** [comment]
I can't replicate this error. It seem it was fixed by this line over here https://github.com/cassandrale179/ci491_project/blob/main/app/src/main/java/com/example/caregiver/TaskFragment.java#L336
