### ISSUE TITLE
The See Progress page is hardcoded

### ISSUE THREAD

**Issue by juihanamshet** [cassandrale179/ci491_project#139]
Caregiver account - juigiver@gmail.com
Caregivee account - juigivee@gmail.com

The See Progress page isn't showing accurate information. Looks hardcoded.
![image](https://user-images.githubusercontent.com/32686593/109366701-28b4d580-7862-11eb-9dac-c6697f7c04db.png)

It should contain the below information
![image](https://user-images.githubusercontent.com/32686593/109366762-45510d80-7862-11eb-87ef-9b81ccd88a10.png)

**Comment by zmcconnell02** [comment]
This was already fixed last week, we just didn't merge it.
