### ISSUE TITLE
Delete caregivee not working correctly

### ISSUE THREAD

**Issue by juihanamshet** [cassandrale179/ci491_project#140]
Caregiver account - juigiver@gmail.com
Caregivee account - juigivee@gmail.com

I deleted caregivee from caregiver's account. I noticed 2 things:
1. The change didn't immediately reflect on caregiver's homepage. I had to reclick on "Home" for the change to be reflected.
2. When I opened the caregivee account, the caregiver still showed up in the "My Caregivers" page.

**Comment by cassandrale179** [comment]
Fixed. 


https://user-images.githubusercontent.com/22923895/109373354-40995300-787c-11eb-8439-a4d661e887ad.mov
