### ISSUE TITLE
Implement Add Media UI Changes using Figma

### ISSUE THREAD

**Issue by Sppurswani** [cassandrale179/ci491_project#190]
Update UI using the Figma screens  - upload media text and icons to select from gallery / take photo.

**Comment by Pratiknaik123** [comment]
I have added "Add Media" and the text can direct the user to UploadMedia class.

<img width="232" alt="Screen Shot 2021-03-30 at 2 48 51 PM" src="https://user-images.githubusercontent.com/47728808/112965625-0e269280-9167-11eb-958c-19d171bb4992.png">
