### ISSUE TITLE
Finish front end of Home Fragment Page (Expandable List)

### ISSUE THREAD

**Issue by cassandrale179** [cassandrale179/ci491_project#30]

**Comment by Pratiknaik123** [comment]
So when you click on "View Profile" -> It directs to the profile page. 

- As of now, when new pages are added, I can update the paths for "Change role", "Set tasks", "See Progress", and "Remove caregiver."
- Also, I just need to pull the usernames from the firebase. (It shouldn't take that long.)

![IMG_5895](https://user-images.githubusercontent.com/47728808/107785988-4a4a9300-6d73-11eb-8427-ad4d80ca4da4.PNG)
![IMG_5896](https://user-images.githubusercontent.com/47728808/107785993-4b7bc000-6d73-11eb-9e87-24697c968ed2.PNG)
