### ISSUE TITLE
Edit Task Page (Caregiver side) 

### ISSUE THREAD

**Issue by cassandrale179** [cassandrale179/ci491_project#41]
This page allows the caregiver to edit a task name, notes, and room associated with that caregivee.

**Comment by Sppurswani** [comment]
Edit Task page (without edits) + corresponding Firebase data

<img width="358" alt="edit-task" src="https://user-images.githubusercontent.com/30156526/108307056-6b4c2300-717b-11eb-9ad9-c33198ad6549.png">
<img width="636" alt="firebase-edit-task1" src="https://user-images.githubusercontent.com/30156526/108307201-81f27a00-717b-11eb-9723-66a24184e6bc.png">

Edit task page (with edits) + corresponding Firebase data + main task page
<img width="343" alt="edit-task2" src="https://user-images.githubusercontent.com/30156526/108307375-acdcce00-717b-11eb-8ff5-66e611253d9b.png">
<img width="701" alt="firebase-edit-task2" src="https://user-images.githubusercontent.com/30156526/108307388-af3f2800-717b-11eb-95e0-97588cdcb23c.png">
<img width="347" alt="task-screen-POST-change" src="https://user-images.githubusercontent.com/30156526/108307430-b82ff980-717b-11eb-8a30-84b8ba859575.png">

Previous Firebase data + Edit task page (with ROOM change) + Post change Firebase data
<img width="732" alt="firebase-edit-task3" src="https://user-images.githubusercontent.com/30156526/108307569-0218df80-717c-11eb-9ec4-1afc940b20b4.png">
<img width="355" alt="edit-task4" src="https://user-images.githubusercontent.com/30156526/108307607-0e04a180-717c-11eb-8f76-d18bee41195d.png">
<img width="687" alt="firebase-edit-task4" src="https://user-images.githubusercontent.com/30156526/108307615-1066fb80-717c-11eb-82e8-d5e1f3ea0cf6.png">
