### ISSUE TITLE
Allow user to upload media on the Add Task page 

### ISSUE THREAD

**Issue by cassandrale179** [cassandrale179/ci491_project#51]

**Comment by Pratiknaik123** [comment]
1. 
![1](https://user-images.githubusercontent.com/47728808/108523982-90b06c80-72f4-11eb-9254-46b4fda20947.png)

2. 
![2](https://user-images.githubusercontent.com/47728808/108523983-90b06c80-72f4-11eb-912d-2090e28b6fb0.png)

3. 
![3](https://user-images.githubusercontent.com/47728808/108523987-927a3000-72f4-11eb-9170-0fc26b02216b.png)

4. 
<img width="1138" alt="4" src="https://user-images.githubusercontent.com/47728808/108523974-8db57c00-72f4-11eb-8920-3eab8479c772.png">

**Comment by cassandrale179** [comment]
1. It should be saved under caregivee ID in which the task is assigned to them with the image.

**Comment by Pratiknaik123** [comment]
1. Works - Needs to be tested
2. Creates new folder under caregiverID
3. Png also works, but gets converted to JPEG when uploading to Storage.
